In [1]:
from random_csv_generator import random_csv
from ugly_csv_generator import uglify
from csv_trimming import trim_csv

In [2]:
csv = random_csv(100)
ugly = uglify(csv, duplicate_schema=False, empty_rows=False, seed=29, )

HBox(children=(IntProgress(value=0, description='Adding empty columns', max=4, style=ProgressStyle(description…

In [3]:
trim_csv(ugly)

,region,province,surname,name,sex,birth_municipality,birth_province,birth_region,birth_cap,birth_province_code,birthdate,address,house_number,cap,municipality,province_code,codice_fiscale,total_debit,payed_debit
0,Puglia,Taranto,Di Domenico,Antonella,F,Pineto,Teramo,Abruzzo,64025,TE,1923-05-28,Corso Annibale,48/50,74100,Taranto,TA,DDMNNL23E68F831L,"11.912,00 €","307,00 €"
1,Puglia,Bari,Rossi,Daniele Salvatore,M,Coreglia Antelminelli,Lucca,Toscana,55025,LU,1941-05-29,Viale Cadorna,67,70033,Corato,BA,RSSDLS41E29C996W,"43.671,00 €","21.713,00 €"
2,Lombardia,Varese,Cecchi,Violete,F,Cantagallo,Prato,Toscana,59025,PO,1985-07-12,Via Castiglioni,6,21040,Carnago,VA,CCCVLT85L52B626X,"75.937,00 €","46.112,00 €"
3,Veneto,Belluno,Caputo,Teresa,F,Martignano,Lecce,Puglia,73020,LE,1928-04-27,Via Roma,25,32040,Borca Di Cadore,BL,CPTTRS28D67E984I,"72.034,00 €","14.576,00 €"
4,Lombardia,Cremona,Colombo,Daniele,M,Carnago,Varese,Lombardia,21040,VA,1984-01-20,Via Roma,221/A,26040,Gussola,CR,CLMDNL84A20B796H,"86.627,00 €","43.897,00 €"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,Campania,Napoli,Martini,Emanuele,M,Poggio A Caiano,Prato,Toscana,59016,PO,1979-12-01,Via Calabritto,6,80121,Napoli,#RIF!,MRTMNL79T01G754N,"16.856,00 €","8.912,00 €"
96,Umbria,Perugia,Dragoni,Alice,F,Tavazzano Con Villavesco,Lodi,Lombardia,26838,LO,1979-08-28,Piazza Mazzini,46,6083,Bastia,PG,DRGLCA79M68F260L,"90.673,00 €","40.253,00 €"
97,Veneto,Treviso,Luppi,Alessio,M,Mirandola,Modena,Emilia Romagna,41037,MO,1921-08-03,Via Della Resistenza,10,31038,Paese,TV,LPPLSS21M03F240F,"49.232,00 €","68,00 €"
98,Lombardia,Cremona,Montanari,Sara,F,Baricella,Bologna,Emilia Romagna,40052,BO,1965-05-28,Via Cavallotti,10,26011,Casalbuttano Ed Uniti,CR,MNTSRA65E68A665D,"66.239,00 €","5.119,00 €"
99,Lombardia,Milano,Traini,Luigi,M,Force,Ascoli Piceno,Marche,63086,AP,1957-12-07,Via Leone Tolstoj,17,20146,Milano,MI,TRNLGU57T07D691T,"97.504,00 €","9.851,00 €"